### PR TITLE
fix: WildFly-swarm tests swarm, not webapp-wildfly

### PR DESCRIPTION
**Pull request by manusa**
Fixes: eclipse/jkube#156

### CODE REVIEW

**Comment by manusa** [comment]
Quarkus tests failing (Quay.io is down) > https://status.quay.io/

**Comment by rohanKanojia** [comment]
Can we use docker hub instead of quay?

**Comment by manusa** [comment]
> Can we use docker hub instead of quay?

Not sure if Quarkus deploys its images there

**Comment by rohanKanojia** [comment]
ah, sorry. Ignore my comment. I thought this is somehow related to the images being pushed here: https://quay.io/organization/jkube . I wanted to have the same on docker hub(since it has bigger community/users)

**Pull request merged**
