### PR TITLE
Adjust WildFly Bootable JAR to slim server and default system options

### PR DESCRIPTION
**Pull request by jfdenise**
Signed-off-by: JF Denise jdenise@redhat.com

### CODE REVIEW

**Review by manusa — APPROVED** [review]

**Comment by manusa** [comment]
This line seems to be causing trouble:
https://github.com/jkubeio/jkube-integration-tests/blob/d1cdb1b095eb2bf2127dff21181a46c38369f224/it/src/test/java/org/eclipse/jkube/integrationtests/wildfly/jar/WildflyJar.java#L45

**Comment by manusa** [comment]
This line is also causing trouble:
https://github.com/jkubeio/jkube-integration-tests/blob/c6d58df9681b279fc551dcc8b4d75e9c7605407e/it/src/test/java/org/eclipse/jkube/integrationtests/wildfly/jar/WildflyJarK8sITCase.java#L128

It should be removed.

Even better if replaced by 
```java
        hasProperty("env", hasItems(allOf(
          hasProperty("name", equalTo("JAVA_ARGS")),
          hasProperty("value", equalTo("-Djboss.bind.address=0.0.0.0"))
        ))),
```

**Review by manusa — CHANGES_REQUESTED** [review]
See comments

**Comment by manusa** [comment]
Just submitted an incremental commit with the suggested changes

**Comment by manusa** [comment]
Still failing:
```
[ERROR] Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.0.1-SNAPSHOT:build (default-cli) on project wildfly-jar-microprofile: Execution default-cli of goal org.eclipse.jkube:kubernetes-maven-plugin:1.0.1-SNAPSHOT:build failed: Error, WildFly bootable JAR generator can't retrieve generated maven local cache, directory /home/user/00-MN/projects/forks/jkube-integration-tests/projects-to-be-tested/wildfly-jar/microprofile/target/bootable-jar-maven-repo doesn't exist. -> [Help 1]
```

**Comment by manusa** [comment]
OK, just found the problem. Apparently in a multimodule project, the `bootable-jar-maven-repo` will be generated in the root directory so in our case:
`./target/bootable-jar-maven-repo` instead of `./projects-to-be-tested/wildfly-jar/microprofile/target/bootable-jar-maven-repo`
so package phase for slim server won't work as expected. Can this be a bug in `wildfly-jar-maven-plugin`.

I'm going to add a workaround for now.

**Review by manusa — APPROVED** [review]

**Comment by manusa** [comment]
Hi @jfdenise I'm going to merge this with the workaround so our test suite is green again.

Please check [my comment](https://github.com/jkubeio/jkube-integration-tests/pull/67#issuecomment-700649202). I'm not sure if this is an issue with the generator (I think it might) or with the WildFly Jar Plugin.

**Comment by jfdenise** [comment]
@manusa , Thank-you! You ran into a bug of the wildfly-jar-maven-plugin. I just logged issue: https://github.com/wildfly-extras/wildfly-jar-maven-plugin/issues/114 Will be fixed in Final release.

**Pull request merged**
