### PR TITLE
test : Add test to verify OpenShift trace logging works

### PR DESCRIPTION
**Pull request by rohanKanojia**
Related to https://github.com/eclipse/jkube/issues/2211

+ Add QuarkusOcTraceEnabledITCase to test suite which verifies
      openshift maven plugin goals with `org.slf4j.simpleLogger.defaultLogLevel`
      property set to trace
+ Add new test project `maven/quarkus/rest-trace-logging-enabled` for
      testing abovementioned integration test

### CODE REVIEW

**Comment by rohanKanojia** [comment]
I think OpenShift E2E test failures are unrelated to changes in my PR. They seem to be failing during setup phase:
```
Pulling image openshift/origin-control-plane:v3.10
error: error pulling Docker image openshift/origin-control-plane:v3.10
Error: Command failed: oc cluster up --routing-suffix="127.0.0.1.${OC_DOMAIN:-nip.io}" 
    at checkExecSyncError (node:child_process:861:11)
    at Object.execSync (node:child_process:932:15)
    at logExecSync (/home/runner/work/_actions/manusa/actions-setup-openshift/e59fe3caa18d7cde81e2ce4797e6549a13f7648c/src/exec.js:8:17)
    at clusterUp (/home/runner/work/_actions/manusa/actions-setup-openshift/e59fe3caa18d7cde81e2ce4797e6549a13f7648c/src/install.js:16:3)
    at startCluster (/home/runner/work/_actions/manusa/actions-setup-openshift/e59fe3caa18d7cde81e2ce4797e6549a13f7648c/src/install.js:18:39)
    at install (/home/runner/work/_actions/manusa/actions-setup-openshift/e59fe3caa18d7cde81e2ce4797e6549a13f7648c/src/install.js:46:3)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/home/runner/work/_actions/manusa/actions-setup-openshift/e59fe3caa18d7cde81e2ce4797e6549a13f7648c/src/index.js:16:3) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 70733,
  stdout: null,
  stderr: null
}
Error: Command failed: oc cluster up --routing-suffix="1[27](https://github.com/jkubeio/jkube-integration-tests/actions/runs/6584473456/job/17889210224?pr=353#step:7:28).0.0.1.${OC_DOMAIN:-nip.io}" 
Error: Command failed: oc cluster up --routing-suffix="127.0.0.1.${OC_DOMAIN:-nip.io}"
```

Maybe it's due to [openshift/origin-control-plane](https://hub.docker.com/r/openshift/origin-control-plane)  image not found on dockerhub

**Comment by manusa** [comment]
It should be possible to rebase this and see if the test passes in oc 3.10 now.

**Comment by manusa** [comment]
The test seems to hang on OpenShift

**Comment by rohanKanojia** [comment]
I'll try to run it locally to see what's wrong.

**Review by manusa — APPROVED** [review]

**Pull request merged**
