### PR TITLE
test : Add E2E test for OpenShift Docker build in Spring Legacy Jar

### PR DESCRIPTION
**Pull request by rohanKanojia**
Add OpenShift Docker build for Spring Boot Fat Jar mode. It verifies only single COPY statement is present when built using fat jar.

### CODE REVIEW

**Review by manusa — CHANGES_REQUESTED** [review]
For this purpose and test scenario, using the `Complete` project instead of the `Zero Config` might make more sense (you are actually providing configuration to the plugin execution.

It also appears that this project had a bootstrapped scenario for OpenShift that doesn't seem to be tested.

**Comment by rohanKanojia** [comment]
> It also appears that this project had a bootstrapped scenario for OpenShift that doesn't seem to be tested.

Could you please elaborate on this? Do you want tests for `oc:resource`, `oc:apply`, `oc:undeploy` as well?

**Comment by manusa** [comment]
> > It also appears that this project had a bootstrapped scenario for OpenShift that doesn't seem to be tested.
> 
> Could you please elaborate on this? Do you want tests for `oc:resource`, `oc:apply`, `oc:undeploy` as well?

I mean that there was already a profile in the pom.xml. I can't remember why it was originally added but tests were never implemented.

There's no need to add the extra-tests for now.

**Comment by rohanKanojia** [comment]
> I mean that there was already a profile in the pom.xml. I can't remember why it was originally added but tests were never implemented.

okay, I can use that profile for adding tests for layered jar. In this case, I need to explicitly disable `<layers>` in the spring boot maven plugin configuration in order to enforce legacy jar behavior.

**Review by manusa — APPROVED** [review]

**Pull request merged**
